/* Generated by AN DISI Unibo */ 
package it.unibo.ctxbarman
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "barmanhost", this, "tearoom.pl", "sysRules.pl"
	)
}

