/* Generated by AN DISI Unibo */ 
package it.unibo.ctxtearoom
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.1.125", this, "tearoom.pl", "sysRules.pl"
	)
}

